let arr = ["jazz" , "blues"];
console.log(arr);
arr.push("rock - n - roll");
console.log(arr);
arr.splice(arr.length - 2 , arr.length - 2 ,"classic");
console.log(arr);
alert(arr.shift(0));
console.log(arr);
arr.unshift("rap" , "reggue");
console.log(arr);
